name: bircher
channels:
  - conda-forge
  - defaults
dependencies:
  - bioformats_jar
  - pip
  - python>=3.10,<3.12
  - pip:
      - aicsimageio[all]
      - aicspylibczi
      - fsspec
      - pandas
      - pyside6-essentials
      - qtpy
      - readlif
